# Generated by Django 5.1.5 on 2025-02-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        help_text="Введите Фамилию, имя и отчество",
                        max_length=200,
                        null=True,
                        verbose_name="ФИО",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        help_text="Укажите должность работника",
                        max_length=250,
                        null=True,
                        verbose_name="Должность",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
            },
        ),
    ]
