# Generated by Django 5.1.5 on 2025-02-08 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Сотрудник",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="is_active",
            field=models.BooleanField(
                default=False, verbose_name="Признак активной задачи"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="is_related",
            field=models.BooleanField(
                default=False, verbose_name="Признак связанной задачи"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="parent_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parent",
                to="tasks.task",
                verbose_name="Родительская задача",
            ),
        ),
    ]
